name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
            
    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/setup-nasm@v1.5.1
    - name: makeasm
      run: nasm -f elf32 kernel.asm -o kasm.o
    - name: makec
      run: gcc -m32 -c kernel.c -o kc.o -lm
    - name: link
      run: ld -m elf_i386 -T link.ld -o kernel kasm.o kc.o
